#%RAML 1.0 SecurityScheme
type: Pass Through
describedBy:
  queryParameters:
    username: string
    password: string
  responses:
    401:
      description: anauthorized
    403:
      description: Forbidden
    404:
      description: Not Found  



    

    
    
    

  



    
