#%RAML 1.0 ResourceTypes
  description: This api is used by <<resourcePathName>>
  get:
    description: It's used by this api to reetrive all details about <<resourcePathName>>
    responses:
      200:
        body:
          application/json:
            example:
              <<exampleReference1>>

   