#%RAML 1.0 NamedExample

-    categoryid: 2
     description: computer and Accessories
     name: com
     price: 120.00
     productid: 11
     video_url: https://www.youtube.com/watch?v=7cXEOWAStq4

-    categoryid: 3
     description: labtop
     name: hp
     price: 500.00
     productid: 20
     video_url: https://www.youtube.com/watch?v=7cXEOWAStq4

     
-   productid: 101
    categoryid: 19
    name: KK G-707 Gaming mouse
    description: The G-707 Gaming mouse is a razor-sharp mouse with 3000 DPI. The mouse comes with a 1-year warranty 
    video_url: https://www.youtube.com/watch?v=3AtDnEC4zak
    price: 7777


