#%RAML 1.0 DataType
  properties:
    addressid: integer
    amount: integer
    created: object
    discountid: integer
    modified: object
    orderid: integer
    status: string
    userid: integer
     
