#%RAML 1.0 NamedExample
orderbyId:
     {
                 "orderid": 100,
                 "userid": 1000,
                 "addressid": 200,
                 "discountid": 12,
                 "created": 1580601600000,
                 "modified": null,
                 "status": "shipped",
                 "amount": 10000
                }