#%RAML 1.0 AnnotationTypeDeclaration
allowedTargets: [Method]
properties:
  usage:
    description: use this ann to understand the details about the online shopping rest api
    default: get
  controller: 
    description: 