#%RAML 1.0 NamedExample
[
  {
    "userid": 2200,
    "email": "hanagaga2121@gmail.com",
    "date_joined": 1582747200000,
    "modified": 1582747201000,
    "type": 1,
    "deleted": false,
    "username": "hana21"
  },
  {
    "userid": 1000,
    "email": "Betty@gmail.com",
    "date_joined": 1589068800000,
    "modified": 1586044800000,
    "type": 5,
    "deleted": false,
    "username": "Bitaniya"
  },]