#%RAML 1.0 NamedExample
[   {
"categoryid": 9,
"description": "firestick",
"name": "Amazon fs",
"price": 35,
"productid": 22,
"video_url": "https://www.youtube.com"
  },
  {
  "productid": 101,
  "categoryid": 19,
  "name": "LG",
  "description": "smart tv",
  "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
  "price": 7777
},
{
  "categoryid": 104,
  "description": "sound bar",
  "name": "samsung audio",
  "price": 230,
  "productid": 32,
  "video_url": "https://www.youtube.com"
}


]