#%RAML 1.0 
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/0597f23a-2852-42ce-a4bc-58dc7c3c2796/ # 
title: online shopping API


types:
  User: !include /datatype/userdatatype.raml
  Userid: !include /datatype/userIddatatype.raml
  Product: !include /datatype/productdatatype.raml
  Category: !include /datatype/categoriesdatatype.raml
  Order: !include /datatype/orderdatatype.raml
 
  
/users:   
  get:
    displayName: getallusers
    description: retrive a list of user 
    responses:
      200:
        body:                    
          application/json:
            type: User[]                            
            examples: !include /example/userExamples.raml
              
  post:     
    displayName: Register users
    description: Registering a user to get user id                   
    body:
      application/json:
        type: User               
        examples: !include /example/userExample.raml          
    responses:
      201:
        description: Created
        body: 
          application/json: 
            type: Userid                   
            examples: !include /example/userIdExample.raml             
             
/products:
  get:
    displayName: getallProducts
    description: retrive all products        
    responses:
       200:
         description: ok
         body: 
           application/json:
             type: Product                                           
             examples: !include /example/productExample.raml
  /{prododuct_id}: 
     get:       
       displayName: Get product by id
       description: Retrieves a product detail based on unique product id                   
       responses:
         200:
           description: OK
           body:
            application/json: 
              type: Product                                          
              examples: !include  /example/productExample.raml
                
                
/categories:              
  get:
    displayName: findallcategories
    description: retrieve all categories of products    
    responses:
      200:
        description: Success
        body:
          application/json: 
            type: Category                                
            examples: !include /example/categoriesExample.raml
             
  /{categories_id }: 
     get:           
       responses:
         200:
           description: ok
           body:
             application/json: 
               type: Category            
               examples: !include /example/categoriesExample.raml             
                 
/orders:
  get:
    displayName: consume orders
    description: get all comsumed orders
    responses:
      200:             
        body:
          application/json:
            type: Order                         
            examples: !include /example/ordersExample.raml
  post:
       displayName: create orders
       description: Adds products into the order
       body:
         application/json:                              
       responses:
         201:
           description: created
           body:
             application/json:
               type: Order                             
               examples: !include /example/ordersExample.raml 
                 
               
  /{order_id}:
    get:
       displayName: Get orders by id
       description: Retrieves order detail based on order id
       responses:
         200:
           description: OK
           body:
             application/json: 
               type: Order                       
               examples: !include /example/ordersExample.raml
                 