#%RAML 1.0 NamedExample
[
  {
    "addressid": 0,
    "amount": 0,
    "created": "2020-06-26y23:16:64",
    "discountid": 0,
    "modified": "2020-06-26y23:16:64",
    "orderid": 0,
    "status": "string",
    "userid": 0
  }
]
