#%RAML 1.0 NamedExample
{   "orderid": 144,
   "userid": 1089,
   "addressid": 201,
   "discountid": 1,
   "created": "2020-06-02T18:09:43.666+00:00",
   "modified": 3,
   "status": "Accepted",
   "amount": 1000,
}
