#%RAML 1.0 SecurityScheme

type: Pass Through
describedBy:
    queryParameters:
      access_key: 
       type: string
       required: true 
      number:  
       type: string
       required: true
      country_code:
        type: string
        required: false
        enum: 
         - ET
         - US
         - AF

    