#%RAML 1.0
title: online-shipping-wo-type

/users:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              [{
                "email": "123@gmail.com",
                "username": "gm"
              }]
  post:
    body:
      application/json:
        example:
          {
            "email": "123@gmail.com",
            "username": "gm"
          }
/users/{id}:
    get:
      responses:
        200:
          body:
            application/json:
              example:
                {
                  "email": "123@gmail.com",
                  "username": "gm"
                }
/products:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              [
                {
                  "productid": 1,
                  "categoryid": 2,
                  "name": "xx",
                   "price": 10
                }
              ]
/products/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            example:              
                {
                  "productid": 3,
                  "categoryid": 4;
                  "price": 10
                }
              
/orders:
  get:
    body:
      application/json:
        example:
          [
            {
              "orderid": 128,
              "userid": 1019,
              "addressid": 201,
              "modified": null,
             "amount": 20
            }
          ]
  post:
    body:
      application/json:
        example:
          {
            "products": [
              {
                "productId": 45,
                "quantity": 19
              }
            ],
            "uid": 11
          }
/orders/{id}:
  get:
    body:
      application/json:
        example:
          {
            "orderid": 16,
            "userid": 10,
            "addressid": 56,
            "discountid": 13,
            "created": "?",
            "modified": null,
            "status": "Accepted",
            "amount": 23
          }
/categories:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              [
                {
                  "categoryid": 8,
                  "name": "zz"
                }
              ]
/categories/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "categoryid": 8,
                "name": "zz"
              }
