#%RAML 1.0 NamedExample

  {
    "addressid": mes123,
    "amount": 2,
      "date": 29,
      "day": Tuesday,
      "hours": 12,
      "minutes": 45,
      "month": 05,
      "nanos": 03,
      "seconds": 27,
      "time": 12,
      "timezoneOffset": GMT-4,
      "year": 2020
    }