#%RAML 1.0 NamedExample
ProExample:
  [
      {
      "productid": 100,
      "categoryid": 10,
      "name": "Amazon laptop",
      "description": "best batter life, 15' laptop, with a 1-year warranty",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC6zak",
      "price": 10000
   },
      {
      "productid": 101,
      "categoryid": 19,
      "name": "KK G-707 Gaming mouse",
      "description": "The G-707 Gaming mouse is a razor-sharp mouse with 3000 DPI. The mouse comes with a 1-year warranty ",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 7777
   },
      {
      "productid": 102,
      "categoryid": 12,
      "name": "Google Home",
      "description": "Google home lets you automate stuff. It's cool.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 9821
   },
      {
      "productid": 103,
      "categoryid": 16,
      "name": "amazon essentials 15' laptop cover",
      "description": "The best you can get around in a handy design and funky look.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 200
   },
      {
      "productid": 104,
      "categoryid": 11,
      "name": "Dell Alienware 007B",
      "description": "The alienware 007B is as it is named, the beast type.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 1600
   },
      {
      "productid": 105,
      "categoryid": 15,
      "name": "KK universal covers",
      "description": "covers for every laptop. Design for every soul.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 550
   },
      {
      "productid": 106,
      "categoryid": 17,
      "name": "khys' clothings",
      "description": "be it umbro or be it jockey, what feels like clothing is khy.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 6412
   },
      {
      "productid": 107,
      "categoryid": 14,
      "name": "KK earbuds",
      "description": "100 hours of battery life. We give more than you can take. Just the best.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 4852
   },
      {
      "productid": 108,
      "categoryid": 13,
      "name": "razor smooth led mouse",
      "description": "The led for kids, the smoothness for men. The DPI for legends.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 852
   },
      {
      "productid": 109,
      "categoryid": 20,
      "name": "H.C verma physics part1,2",
      "description": "if you know, you know. it's what legends look for when they wanna get goosebumps.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 888
   },
      {
      "productid": 110,
      "categoryid": 18,
      "name": "BARA",
      "description": "it's not ZARA, it was always BARA. #BEBARA",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 999
   },
      {
      "productid": 111,
      "categoryid": 21,
      "name": "Nike",
      "description": "its the best shoes you will find in the world",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 1500
   },
      {
      "productid": 112,
      "categoryid": 22,
      "name": "CHCH",
      "description": "ultimate femme fatale fragrance",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 1000
   }
]