#%RAML 1.0 NamedExample
UserExample:
  [
      {
      "userid": 900,
      "email": "faye@hotmail.com",
      "date_joined": "2020-02-26T20:00:00.000+00:00",
      "modified": "2020-02-26T20:00:01.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "fayz"
   },
      {
      "userid": 1000,
      "email": "Betty@gmail.com",
      "date_joined": "2020-05-10T00:00:00.000+00:00",
      "modified": "2020-04-05T00:00:00.000+00:00",
      "type": 5,
      "deleted": false,
      "username": "Bitaniya"
   },
      {
      "userid": 1001,
      "email": "kapasikush@gmail.com",
      "date_joined": "2015-09-16T11:22:11.000+00:00",
      "modified": "2017-05-26T23:26:15.000+00:00",
      "type": 7,
      "deleted": false,
      "username": "keval kapasi"
   },
      {
      "userid": 1002,
      "email": "kapasiyash@gmail.com",
      "date_joined": "2018-12-05T00:23:06.000+00:00",
      "modified": "2019-03-06T22:26:15.000+00:00",
      "type": 6,
      "deleted": false,
      "username": "yash kapasi"
   },
      {
      "userid": 1003,
      "email": "abc@gmail.com",
      "date_joined": "2010-05-19T14:36:36.000+00:00",
      "modified": "2015-05-03T00:00:11.000+00:00",
      "type": 5,
      "deleted": false,
      "username": "john green"
   },
      {
      "userid": 1004,
      "email": "xyz@yahoo.com",
      "date_joined": "2014-07-30T20:27:58.000+00:00",
      "modified": "2015-04-14T20:27:58.000+00:00",
      "type": 4,
      "deleted": false,
      "username": "kylie jenner"
   },
      {
      "userid": 1005,
      "email": "yeddidaa@hotmail.com",
      "date_joined": "2019-11-24T14:30:25.000+00:00",
      "modified": "2020-03-22T06:30:40.000+00:00",
      "type": 7,
      "deleted": false,
      "username": "selina gumej"
   },
      {
      "userid": 1006,
      "email": "kutyperi@junkmail.com",
      "date_joined": "2011-08-19T09:34:41.000+00:00",
      "modified": "2015-09-14T20:55:45.000+00:00",
      "type": 4,
      "deleted": false,
      "username": "katy pery"
   },
      {
      "userid": 1007,
      "email": "camilucabal@gamil.com",
      "date_joined": "2006-10-06T23:00:51.000+00:00",
      "modified": "2009-05-03T00:59:51.000+00:00",
      "type": 7,
      "deleted": false,
      "username": "camilla cabello"
   },
      {
      "userid": 1008,
      "email": "bashve@bas.com",
      "date_joined": "2005-12-07T11:00:30.000+00:00",
      "modified": "2008-10-13T17:46:46.000+00:00",
      "type": 1,
      "deleted": true,
      "username": "modi ji"
   },
      {
      "userid": 1009,
      "email": "16gdb@jpmc.com",
      "date_joined": "2003-03-10T20:40:38.000+00:00",
      "modified": "2004-08-19T20:40:59.000+00:00",
      "type": 1,
      "deleted": true,
      "username": "salman dimon"
   },
      {
      "userid": 1010,
      "email": "qwerty@keyboard.com",
      "date_joined": "2011-07-09T00:00:05.000+00:00",
      "modified": "2013-09-23T13:00:59.000+00:00",
      "type": 2,
      "deleted": false,
      "username": "android google"
   },
      {
      "userid": 1011,
      "email": "test@test.com",
      "date_joined": "2020-05-24T06:26:42.000+00:00",
      "modified": "2020-05-24T06:26:42.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "test"
   },
      {
      "userid": 1012,
      "email": "test1@test.com",
      "date_joined": "2020-05-24T06:27:04.000+00:00",
      "modified": "2020-05-24T06:27:04.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "test1"
   },
      {
      "userid": 1013,
      "email": "test23@test.com",
      "date_joined": "2020-05-24T06:57:19.000+00:00",
      "modified": "2020-05-24T06:57:19.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "yashtest"
   },
      {
      "userid": 1014,
      "email": "yash@test.com",
      "date_joined": "2020-05-24T07:31:05.000+00:00",
      "modified": "2020-05-24T07:31:05.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "yashtest123"
   },
      {
      "userid": 1015,
      "email": "kadi@gmail.com",
      "date_joined": "2020-05-24T08:12:10.000+00:00",
      "modified": "2020-05-24T08:12:10.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "kadida"
   },
      {
      "userid": 1016,
      "email": "hanan.amu@gmail.com",
      "date_joined": "2020-05-24T21:41:53.000+00:00",
      "modified": "2020-05-24T21:41:53.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "abdul"
   },
      {
      "userid": 1017,
      "email": "test",
      "date_joined": "2020-05-25T06:33:18.000+00:00",
      "modified": "2020-05-25T06:33:18.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "test"
   },
      {
      "userid": 1018,
      "email": "testabc@gmail.com",
      "date_joined": "2020-05-25T08:06:02.000+00:00",
      "modified": "2020-05-25T08:06:02.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "yash"
   },
      {
      "userid": 1019,
      "email": "ted@gmail.com",
      "date_joined": "2020-05-26T02:00:39.000+00:00",
      "modified": "2020-05-26T02:00:39.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "ted2020"
   },
      {
      "userid": 1020,
      "email": "merkeb@gmail.com",
      "date_joined": "2020-05-02T10:00:32.000+00:00",
      "modified": "2020-05-26T02:00:39.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "mkb"
   },
      {
      "userid": 1021,
      "email": "net@gmail.com",
      "date_joined": "2020-05-02T00:00:00.000+00:00",
      "modified": "2020-05-23T00:00:00.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Netsanet"
   },
      {
      "userid": 1022,
      "email": "selam_now@gmail.com",
      "date_joined": "2020-05-02T00:00:00.000+00:00",
      "modified": "2020-05-02T00:00:00.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Selam"
   },
      {
      "userid": 1023,
      "email": "testbac@yash.com",
      "date_joined": "2020-05-26T12:52:18.000+00:00",
      "modified": "2020-05-26T12:52:18.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "pop"
   },
      {
      "userid": 1024,
      "email": "qw@qw.com",
      "date_joined": "2020-05-26T12:56:35.000+00:00",
      "modified": "2020-05-26T12:56:35.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "as"
   },
      {
      "userid": 1025,
      "email": "test@testdsdsds.com",
      "date_joined": "2020-05-26T12:58:09.000+00:00",
      "modified": "2020-05-26T12:58:09.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1026,
      "email": "test@soap1.com",
      "date_joined": "2020-05-26T13:02:36.000+00:00",
      "modified": "2020-05-26T13:02:36.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1027,
      "email": "test@soap2.com",
      "date_joined": "2020-05-26T13:04:23.000+00:00",
      "modified": "2020-05-26T13:04:23.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1028,
      "email": "test@soap3.com",
      "date_joined": "2020-05-26T13:06:20.000+00:00",
      "modified": "2020-05-26T13:06:20.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1029,
      "email": "test@soap4.com",
      "date_joined": "2020-05-26T13:07:51.000+00:00",
      "modified": "2020-05-26T13:07:51.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1030,
      "email": "test@soap5.com",
      "date_joined": "2020-05-26T13:13:24.000+00:00",
      "modified": "2020-05-26T13:13:24.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1031,
      "email": "test@soap6.com",
      "date_joined": "2020-05-26T13:14:51.000+00:00",
      "modified": "2020-05-26T13:14:51.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "popo"
   },
      {
      "userid": 1032,
      "email": "jitseid@gmail.com",
      "date_joined": "2020-05-26T18:24:13.000+00:00",
      "modified": "2020-05-26T18:24:13.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "jitu"
   },
      {
      "userid": 1033,
      "email": "hiwot@gmail.com",
      "date_joined": "2020-05-26T18:24:13.000+00:00",
      "modified": "2020-05-26T18:24:13.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Hiwot"
   },
      {
      "userid": 1034,
      "email": "priyanka@gmail.com",
      "date_joined": "2020-05-26T19:34:44.000+00:00",
      "modified": "2020-05-26T19:54:16.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "fayz"
   },
      {
      "userid": 1035,
      "email": "string",
      "date_joined": "2020-05-26T22:31:34.000+00:00",
      "modified": "2020-05-26T22:31:34.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "string"
   },
      {
      "userid": 1036,
      "email": "keb@gmail.com",
      "date_joined": "2020-05-26T22:33:05.000+00:00",
      "modified": "2020-05-26T22:33:05.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "kebs"
   },
      {
      "userid": 1037,
      "email": "amen @gmail.com",
      "date_joined": "2020-05-26T22:33:05.000+00:00",
      "modified": "2020-05-26T22:33:10.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "amen"
   },
      {
      "userid": 1038,
      "email": "ted23@gmail.com",
      "date_joined": "2020-05-27T06:10:17.000+00:00",
      "modified": "2020-05-27T06:10:17.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "ted2020"
   },
      {
      "userid": 1039,
      "email": "Mer@gmail.com",
      "date_joined": "2020-05-27T08:22:34.000+00:00",
      "modified": "2020-05-27T08:22:34.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Merhawit"
   },
      {
      "userid": 1040,
      "email": "Val@gmail.com",
      "date_joined": "2020-05-27T08:43:34.000+00:00",
      "modified": "2020-05-27T08:43:34.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Vallee"
   },
      {
      "userid": 1041,
      "email": "sude@gmail.com",
      "date_joined": "2020-05-27T17:02:58.000+00:00",
      "modified": "2020-05-27T17:02:58.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "su123"
   },
      {
      "userid": 1042,
      "email": "lulay@gmail.com",
      "date_joined": "2020-05-27T17:48:01.000+00:00",
      "modified": "2020-05-27T17:48:01.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "lulay"
   },
      {
      "userid": 1044,
      "email": "sajuyabatulij",
      "date_joined": "2020-05-27T17:49:42.000+00:00",
      "modified": "2020-05-27T17:49:42.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Sajulovesdaddy"
   },
      {
      "userid": 1045,
      "email": "anteneh@gmail.com",
      "date_joined": "2020-05-27T21:16:06.000+00:00",
      "modified": "2020-05-27T21:16:06.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "ant2020"
   },
      {
      "userid": 1052,
      "email": "Vall@gmail.com",
      "date_joined": "2020-05-28T12:36:34.000+00:00",
      "modified": "2020-05-28T12:36:34.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Merval"
   },
      {
      "userid": 1053,
      "email": "mikesam@gmail.com",
      "date_joined": "2020-05-28T20:31:04.000+00:00",
      "modified": "2020-05-28T20:31:04.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "mike123"
   },
      {
      "userid": 1056,
      "email": "nebiha123@gmail.com",
      "date_joined": "2020-05-29T01:13:09.000+00:00",
      "modified": "2020-05-29T01:13:09.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "neb123"
   },
      {
      "userid": 1057,
      "email": "bele@gmail.com",
      "date_joined": "2020-05-29T01:42:18.000+00:00",
      "modified": "2020-05-29T01:42:18.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "bwal"
   },
      {
      "userid": 1067,
      "email": "xyz@gmail.com",
      "date_joined": "2020-05-29T05:17:44.000+00:00",
      "modified": "2020-05-29T05:17:44.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "xyz"
   },
      {
      "userid": 1068,
      "email": "belo@gmail.com",
      "date_joined": "2020-05-29T07:17:38.000+00:00",
      "modified": "2020-05-29T07:17:38.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "belo"
   },
      {
      "userid": 1069,
      "email": "berhanemeron61@gmail.com",
      "date_joined": "2020-05-29T21:38:54.000+00:00",
      "modified": "2020-05-29T21:38:54.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "merry"
   },
      {
      "userid": 1076,
      "email": "Nathaliyan20@gmail.com",
      "date_joined": "2020-05-29T23:29:57.000+00:00",
      "modified": "2020-05-29T23:29:57.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "merry"
   },
      {
      "userid": 1077,
      "email": "Nathan20@gmail.com",
      "date_joined": "2020-05-29T23:31:38.000+00:00",
      "modified": "2020-05-29T23:31:38.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Zulu"
   },
      {
      "userid": 1078,
      "email": "amen@gmail.com",
      "date_joined": "2020-05-30T00:37:00.000+00:00",
      "modified": "2020-05-30T00:37:00.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "amen"
   },
      {
      "userid": 1079,
      "email": "mes@hotmail.com",
      "date_joined": "2020-05-30T17:06:56.000+00:00",
      "modified": "2020-05-30T17:06:56.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "mes123"
   },
      {
      "userid": 1080,
      "email": "soz@gmail.com",
      "date_joined": "2020-05-31T15:07:30.000+00:00",
      "modified": "2020-05-31T15:07:30.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "soz"
   },
      {
      "userid": 1081,
      "email": "mbb@gmail.com",
      "date_joined": "2020-05-31T15:19:23.000+00:00",
      "modified": "2020-05-31T15:19:23.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "Mob"
   },
      {
      "userid": 1082,
      "email": "simo12@gmail.com",
      "date_joined": "2020-05-31T15:32:55.000+00:00",
      "modified": "2020-05-31T15:32:55.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "simo123"
   },
      {
      "userid": 1083,
      "email": "simret9@gmail.com",
      "date_joined": "2020-05-31T16:25:01.000+00:00",
      "modified": "2020-05-31T16:25:01.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "simret12"
   },
      {
      "userid": 1084,
      "email": "test@gmail.com",
      "date_joined": "2020-05-31T21:56:57.000+00:00",
      "modified": "2020-05-31T21:56:57.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "helen123"
   },
      {
      "userid": 1085,
      "email": "kebebeb@gmail.com",
      "date_joined": "2020-06-01T00:40:09.000+00:00",
      "modified": "2020-06-01T00:40:09.000+00:00",
      "type": 1,
      "deleted": false,
      "username": "kebe3"
   }
]