#%RAML 1.0 NamedExample

  [
      {
      "productid": 100,
      "categoryid": 10,
      "name": "Amazon laptop",
      "description": "best batter life, 15' laptop, with a 1-year warranty",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC6zak",
      "price": 10000
   },
      {
      "productid": 101,
      "categoryid": 19,
      "name": "KK G-707 Gaming mouse",
      "description": "The G-707 Gaming mouse is a razor-sharp mouse with 3000 DPI. The mouse comes with a 1-year warranty ",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 7777
   }]
