#%RAML 1.0 NamedExample
  
 [ {
                "email":"bella@gmail.com",
                "username":"bella"},
                
               { "email":"belay@gmail.com",
                "username":"belay"

          

          }]