#%RAML 1.0 Library
usage:
types:
 catagories: !include catagories.raml
 orders: !include /DataTypes/orders.raml
 products: !include products.raml
 userId: !include userId.raml
 users: !include users.raml
 orderRequest: !include /DataTypes/orderRequest.raml
 
 