#%RAML 1.0 DocumentationItem
title: onlineshopping Restfull API documentation 
content: In this API the customer self-registers by passing username and email to generate a unique user id. Customers are allowed to browse different products and place an order from different categories. 
 This API REST support different http methods for different source and gives response type   
 the reources used in this api raml were users,order,product and   categories and the methods are only get and post.
 