#%RAML 1.0 NamedExample
  [
              {
             "categoryid": 11,
               "name": "laptops"
              },
              {
               "categoryid": 12,
               "name": "home electronics"
               },
             {
              "categoryid": 14,
              "name": "mobile accesories"
            },
            {
              "categoryid": 15,
              "name": "laptop skins"
            },
            {
              "categoryid": 16,
              "name": "laptop covers"
            },
            {
              "categoryid": 17,
              "name": "men's clothing"
            },
            {
              "categoryid": 18,
              "name": "women's wardrobe"
            },
            {
              "categoryid": 19 ,
              "name": "gaming geeks"
            },
            {
              "categoryid": 20,
              "name": "study buddy"
            }
          ]