#%RAML 1.0 ResourceType
type:
  onlineshopping.collectionid :
    responsegettype : onlineshopping.catagory
    getreference1 : --!include /examples/catagory-id-example.raml
    statuscode-get :  onlineshopping.statuscode 
    