#%RAML 1.0 ResourceType
type:
  onlineshopping.getcollection :
    responsegettype : onlineshopping.catagory[]
    getreference1 : --!include //examples/catagory.raml
    statuscodeget :  onlineshopping.statuscode   