#%RAML 1.0 ResourceType
type :

  onlineshopping.collectionid :
    responsegettype : onlineshopping.catagory
    getreference1 : --!include /examples/orderid-example.raml
    statuscodeget :  onlineshopping.statuscode 