#%RAML 1.0 ResourceType
onlineshopping.getcollection :
  responsegettype : onlineshopping.items[]
  getreference1 : --!include /examples/products.raml
  statuscodeget :  onlineshopping.statuscode          
    