#%RAML 1.0 ResourceType
type:
  
  onlineshopping.collectionid:
    responsegettype : onlineshopping.items
    getreference1 : --!include  /examples/productid-.raml 
    statuscodeget :  onlineshopping.statuscode 