#%RAML 1.0 ResourceType
type:
  onlineshopping.collection :
    requestposttype : onlineshopping.user
    postReference1 : -- !include //examples/userid-example.raml
    responseposttype : onlineshopping.userid
    postreference2 : --!include /examples/user-id-example.raml
    statuscodepost : onlineshopping.statuscode
    responsegettype : onlineshopping.user[]
    getreference1 : --!include /examples/user-example.raml
    statuscodeget :  onlineshopping.statuscode          