#%RAML 1.0 ResourceType
type:
  onlineshopping.collectionid :
   responsegettype : onlineshopping.user
   getreference1 : --!include /data-types/userid.raml
   statuscodeget :  onlineshopping.statuscode 
