#%RAML 1.0 NamedExample
{
  "orderid": 10,
  "userid": 26,
  "addressid": "Addis Ababa",
  "discountid": 1,
  "created": "2020-06-03T04:10:26.000+00:00",
  "modified": "null",
  "status": "Accepted",
  "amount": 6
}