#%RAML 1.0 NamedExample

[
  {
    "categoryid": 30,
    "description": "tv",
    "name": "panasonic",
    "price": 120,
    "productid": 5,
    "video_url": "www.panasonic.com"
  },
  {
    "categoryid": 50,
    "description": "phone",
    "name": "apple",
    "price": 700,
    "productid": 2,
    "video_url": "www.apple.com"
  }

]