#%RAML 1.0 NamedExample
 
{   
         "categoryid": 10,
            "description": "tablet",
            "name": "apple",
            "price": 250,
            "productid": 100,
            "video_url": " https://www.youtube.com/watch? v=3AtDnEC4zak" 
             
          }