#%RAML 1.0 NamedExample
product:
                                     {
    "productid": 100,
    "categoryid": 10,
    "name": "Amazon laptop",
    "description": "best batter life, 15' laptop, with a 1-year warranty",
    "video_url": "https://www.youtube.com/embed/Ic-Y3osvnFk",
    "price": 10000
  }