#%RAML 1.0 DataType
type: object
properties: 
  address: integer
  amount: integer
  created: integer
  date: integer
  day: string
  hours: datetime                 
  minutes: datetime
  month: datetime
  nanos: datetime
  seconds: datetime
  time: datetime
  timezoneOffset: string
  year: string 

 