#%RAML 1.0 Trait
responses:
  404:
    body:
      application/json:
        examples:
          "msge": "User requested a resource which does not exist."
  210:
    body:
      application/json:
        examples:
          "msge": "User did not provide a phone number." 
  101:
    body:
      application/json:
        examples:
          "msge": "User entered an invalid Access Key."




    
      
          
         
          

  
  
  

  
