#%RAML 1.0 Trait
responses:
  401:
    body:
      application/json:
        example:
          {"message":"unauthorized"}
  403:
    body:
      application/json:
        example:
          {"message":"forbidden"}
  404:
    body:
      application/json:
        example:
          {"message":"Not found"}