#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: this api supports oauth security
describedBy:
  headers:
    Authorization: 
     description: user has to send token to access any resource 
     type: string
  queryParameters:
    access-token :
      description: user has to send valid token with the query
      type : string
  responses:
    200:
      description: ok
    401:
      description: bad or expired access token is used
    403:
      description: not allowed to access the resourse

        