#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f3661354-866d-4756-927a-52e7763dc8f6/ # 
title: Onlineshoping
/Categories:
    get:
      responses:
        200:
          body:
            application/json:
              example:
                {
    "categoryid": 0,
    "name": "food"
  }
 
