#%RAML 1.0 NamedExample
 [{"username":"teme", "email": "rewina@gmail.com",
  "age":34},
  {"username":"teme", "email": "tem@gmail.com",
  "age":4},
  {"username":"teme", "email": "sime@gmail.com",
  "age":3}]
