#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: This API support oauth security
describedBy:
  headers:
    Authorization: 
     description:  user have to send token to acess any resource
     type: string
  queryParameters:
    acess_token:
      description: user have to send vaild token with the query param
      type: string
  responses:
    401:
      description: bad or expired token is used
    403:
      description: not allowed to acess the resource