#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/5d5a3381-9735-451a-a055-3bb715b0fcb1/ # 
title: ONLINE-SHOPPING-API

types:
  user : !include /data-types/userdatatype.raml
  userid : !include /data-types/userid.raml
  items : !include /data-types/productsdataType.raml
  order : !include /data-types/orderdataType.raml
  catagory : !include /data-types/catagorydataType.raml
  orderrequest : !include /data-types/order-requests-Type.raml
resourceTypes:
  collection : !include /resource/collection.raml
  collectionid : !include /resource/collectionid.raml
  get-collection : !include /resource/getcollection.raml
  user-collection : !include //resource/usercollection.raml
  user-id-collection : !include /resource/useridcollection.raml
  product-collection : !include /resource/productscollection.raml
  product-id-collection : !include /resource/productidcollection.raml
  orders-collection : !include /resource/orderscollection.raml
  order-id-collection : !include /resource/orderidcollection.raml
  catagory-collection : !include /resource/catagorycollection.raml
  catagory-id-collection : !include /resource/catagoryidcollection.raml

traits:
  statuscode : !include /trait/404-trait.raml 
securitySchemes:
  oath : !include /security/securityScheme.raml   
     
 

/users : 
 get:
   responses:
    200:
        body:
          application/json:
            type: user[]
            examples: !include /examples/user-example.raml
 is: 
    - statuscode:
      
       
 post:
   body:
      application/json:
        type: user
        examples: !include //examples/userid-example.raml
   responses:
      201:
        body:
          application/json:
            type: userid
            examples: !include /examples/user-id-example.raml
/users/{id} :
  description: id
  uriParameters:
     id:
  get:
     responses:
        200:
          body:
            application/json: 
             type: user
             examples: !include /examples/userid-example.raml
  is: 
    - statuscode:
      
                

 
/products:
  get:
    responses:
      200:
        description: ok
        body:
          application/json:
            type: items[]
            examples: !include /examples/products.raml
  is: 
    - statuscode:
                
/products/{id} :
  uriParameters:
    id:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            type: items
            examples: !include  /examples/productid-.raml 
  is: 
    - statuscode:
                              
/orders:
  get:
    responses:
      200:
        body:
          application/json: 
            type: order[]
            examples: !include /examples/order.raml
  is: 
    - statuscode:
                
  post:
    securedBy: oath
    body:
      application/json:
        type: orderrequest
        examples: !include /examples/order-request-example.raml
    responses:
      201:
       body:
          application/json:
            type : orderrequest
            examples : !include /examples/order-request-example.raml
    is: 
      - statuscode
              
/orders/{id}:
   uriParameters:
      id:
        type: integer
   get:
     responses:
       200:
         body:
           application/json:
             type: order
             examples: !include /examples/orderid-example.raml
   is: 
    - statuscode:
                 
/categories:
  get:
    responses:
      200:
       
        body:
          application/json:
            type: catagory[]
            examples: !include /examples/catagory.raml
  is: 
    - statuscode:
               
/categories/{id} :
  uriParameters:
    id:
      type: integer
  get:
     responses:
        200:
          
          body:
            application/json:
              type: catagory
              examples: !include /examples/catagory-id-example.raml
                
         
  
 
       
         