#%RAML 1.0 SecurityScheme
type: OAuth 1.0
description: this API suports oauth security
describedBy:
  headers:
    Authorization:
      description: user have to send to access any resource
      type: string
  queryParameters:
    access_token:
      description: user have to send valid token with the query parameter
      type: string
  responses:
    401:
      description: bad or expired token is used
    403:
      description: not allowed to access the resource

