#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/2ebf1790-78c3-478b-b66b-fec4702bfc67/ # 
title: ONLINE-SHOPPING-API


/users :
 
    
  get:
    responses:
      200:
        body:
          application/json:
            examples: !include /example.raml

/users/{id} : 
   description: id
   get:
     responses:
        200:
          body:
            application/json:
              examples: !include example.raml
              
   post:
      body:
        application/json:
          examples: !include example.raml

/products:
  get:
    responses:
      200:
        description: ok
        body:
          application/json:
            examples: !include /products.raml
              
            
      401:
        description: anautoried  
      403:
        description: forbidden
      404:
        description: not found
/products/{id} :
  get:
    responses:
      200:
        body:
          application/json:
            examples: !include products.raml
              
          

      401:
        description: Anautorized
      403:
        description: Forbidden
      404:
        description: Not Found                   
/consume:
  get:
    responses:
      200:
        description: ok
        body:
          application/json:
            example:
              "yes"
      401:
        description: unautorized
      403:
        description: Forbidden
      404:
        description: Not Found  
/orders:
  get:
    responses:
      200:
        description: Ok
        body:
          application/json:
            examples: !include order.raml
                  
      401:
        description: Unautorized
      403:
        description: Forbidden
      404:
        description: Not Found  
  post:
    body:
      application/json:
        example:
          {
  "products": [
    {
      "productId": 2,
      "quantity": 5
    }
  ],
  "uid": 123
}
    responses:
      200:
        description: Ok
        body:
          application/json:
            example :
              "CREATED"
             
/orders/{uid}:
     get:
       responses:
        200:
          description: Ok
          body:
            application/json:
              examples: !include order.raml
                
                

        401:  
          description: unautorized
        403:
         description: Forbidden
        404:
          description: Not Found  
/orders/{id}:
    get:
     responses:
        200:
          description: Ok
          body:
            application/json:
              examples: !include order.raml
                
        401:  
          description: unautorized
        403:
         description: Forbidden
        404:
         description: Not Found  
/categories:
  get:
    responses:
      200:
        description: Ok
        body:
          application/json:
            examples: !include catagory.raml
              
      401:  
          description: unautorized
      403:
         description: Forbidden
      404:
         description: Not Found  
  /categories/{id} :
    get:
     
      responses:
        200:
          description: Ok
          body:
            application/json:
              examples: !include catagory.raml
                
              
 
        401:  
          description: unautorized
        403:
         description: Forbidden
        404:
         description: Not Found  