#%RAML 1.0 NamedExample
    
   [ {
      "categoryid": 20,
      "description": "printer",
      "name": "mac",
      "price": 2000,
      "productid": 12,
      "video_url": "www.mac.com"
    },
    {
      "categoryid": 20,
      "description": "printer",
      "name": "mac",
      "price": 2000,
      "productid": 12,
      "video_url": "www.mac.com"
    }]
    
    