#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/20c81ee1-55eb-436b-98c9-6c5fade17009/ # 
title: onlineshoping1
securitySchemes: 
  
traits:
  responces: !include traits/Responses.raml
types:
   catagorydatatype: !include /DataType/Catagory.raml
   Orderdatatype: !include  /DataType/Order.raml
   ProductType: !include  /DataType/Product.raml
   Userdatatype: !include /DataType/userID1.raml
/category:
  get:
    responses:
      200:
        body:
          application/json:
            type: catagorydatatype []
            example: !include Example/catagry.json
  is: [responces]
  /{Category ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: catagorydatatype
              example: !include /Example/Catagoryid.raml
      is: [responces]        
/order:
  get:
    description: Get all order
    responses:
      200:
        body:
          application/json:
            type:  Orderdatatype []
            example: !include Example/GetAllOrders.raml
    is: [responces]
  post:
    responses:
      200:
        body:
          application/json:
            type: !include DataType/Order.raml
            example: !include Example/orderpost.raml
    is: [responces]
              
      
  /{Order UID}:
    get:
      description: Get order by user ID
      responses:
        200:
          body:
            application/json:
              type: Orderdatatype []
              example: !include Example/GetOrderByUserID.raml
    is: [responces]
                
              
/{order ID}:
  get:
    description: Get order by ID
    responses:
      200:
        body:
          application/json:
            type: Orderdatatype
            example: !include Example/OrderID.raml
    is: [responces]

/product:
  get:
    responses:
      200:
        body:
          application/json:
            type: ProductType []
            example: !include Example/Product.raml
    is: [responces]
              
  /{product ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: ProductType 
              example: !include Example/ProductByID.raml
      is: [responces]
                
/User:
  get:
    responses:
      200:
        body:
          application/json:
            type: Userdatatype []
            example: !include Example/User.json
    is: [responces]
  post:
    responses:
      200:
        body:
          application/json:
            type: Userdatatype
            example: !include Example/userpost.raml
    is: [responces]
              
              
  /{User ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type:  Userdatatype 
              example: !include Example/userID1.raml
      is: [responces]

