#%RAML 1.0 ResourceType
post:
  description: Create <<resourcePathName>>
  body:
   application/json:
      type: <<request-post-type>>
      examples:
        input: <<request-post-example>>
  responses:
    201:
      body:
        application/json:
          type: <<response-post-type>>
          examples:
            output: <<response-post-example>>
  securedBy: [basic]
  is:
    - <<trait-post-error>>
get:
  description: 
  responses:
    200:
      body:
        application/json:
          type: <<response-get-type>>
          examples:
            output: <<response-get-example>>
  is:
    - <<trait-get-error>>
    
        