#%RAML 1.0 Library
usage: 
types:
  users: !include users.raml
  usersID: !include usersID.raml
  orders: !include orders.raml
  products: !include Products.raml
  category: !include category.raml
  OrderRequests: !include OrderRequests.raml
