#%RAML 1.0 Library
usage: apply this type for the resources of online-shopping.
types:
  categories: !include categories.raml
  orders: !include ordes.raml
  products: !include products.raml
  userID: !include userID.raml
  users: !include users.raml
  orderRequests: !include orderRequests.raml