#%RAML 1.0 Overlay
extends: ../online-shopping.raml
title: online-shopping overview
documentation:
  - title: overview
    content: the document defines about the onleine shopping
    /product:
      content: 
