#%RAML 1.0 ResourceType
type:
  online-shopping.collectionget:
    request-get-type:  online-shopping.product[]
    request-get-example: !include ../examples/products/getproducts.raml
    error-trait-get: online-shopping.errortrait
     
           