#%RAML 1.0 ResourceType
type:
  online-shopping.collectionget:
    request-get-type: online-shopping.catagories[]
    request-get-example: !include ../examples/categories/getcategory.raml
    error-trait-get: online-shopping.errortrait
    

            