#%RAML 1.0 ResourceType
type:
  online-shopping.collectionget:
    request-get-type: online-shopping.userid
    request-get-example: !include ../examples/user/getuserid.raml
    error-trait-get: online-shopping.errortrait

               