#%RAML 1.0 ResourceType
type:
  online-shopping.collectionget:
    request-get-type: online-shopping.catagoriesid
    request-get-example: !include ../examples/categories/getcategoryid.raml
    error-trait-get: online-shopping.errortrait
    

