#%RAML 1.0 ResourceType
type:
  online-shopping.collectionget:
    
    request-get-type:  online-shopping.productid
    request-get-example: !include ../examples/products/getproductid.raml
    error-trait-get: online-shopping.errortrait
