#%RAML 1.0 ResourceType
type:
  online-shopping.collectiongetandpost:
    request-post-type: online-shopping.orderspostrequest
    request-post-example: !include ../examples/orders/postorders.raml
    response-post-type: online-shopping.orederpostresponse
    response-post-example: !include ../examples/orders/postresponseorders.raml
    error-trait-post: online-shopping.errortrait
    response-get-type: online-shopping.orders[]
    response-get-example: !include ../examples/orders/getorders.raml
    error-trait-get: online-shopping.errortrait

 
 