#%RAML 1.0 NamedExample

 [
  {
    "addressid": "0",
    "amount": 0 ,
    "created": 2016-02-28T16:41:41.090Z,
    "discounted": 0,
    "modified": "9999-12-31 23:59:59",
    "orderid": 0,
    "status": "string",
    "userid": 0
  }
]