#%RAML 1.0 NamedExample
order:
 [
  {
    "orderid":51
    "userid":1
    "addressid":201
    "discountid":6
    "created": 2019-05-15 12:39:30
    "modified": 2019-05-15 12:39:30
    "status": "shipped"
    "amount": 550
  }
    {
    "orderid":52
    "userid":2
    "addressid":202
    "discountid":8
    "created": 2019-05-16 12:39:30
    "modified": 2019-05-16 12:41:30
    "status": "completed "
    "amount": 45
  }
    {
    "orderid":53
    "userid":3
    "addressid":203
    "discountid":4
    "created": 2020-05-15 12:39:30
    "modified": 2020-05-15 12:39:30
    "status": "delivered"
    "amount": 152 
  }
    {
    "orderid":54
    "userid":12
    "addressid":221
    "discountid":12
    "created": 2020-10-15 12:39:30
    "modified": 2020-10-15 12:39:30
    "status": "shipped"
    "amount": 5
  }
    {
    "orderid":55
    "userid":8
    "addressid":205
    "discountid":10
    "created": 2019-12-15 12:39:30
    "modified": 2019-12-15 12:39:30
    "status": "shipped"
    "amount": 52
  }
    {
    "orderid":56
    "userid":11
    "addressid":207
    "discountid":6
    "created": 2019-05-22 12:39:30
    "modified": 2019-05-22 12:39:30
    "status": "completed"
    "amount": 250
  }
]