#%RAML 1.0 NamedExample
Orders: {
            "products": [
              {
                "productId": 0,
                "quantitiy": 0
              }
            ],
            "uid": 0
          }