#%RAML 1.0 NamedExample
user:
  [
  {"username": "test", 
  "email":"test@gmail.com"},
   {"username": "jon", 
  "email":"jont@gmail.com"},
   {"username": "rob", 
  "email":"robt@gmail.com"},
   {"username": "bob", 
  "email":"bob@gmail.com"},
  
   {"username": "kate", 
  "email":"kate@gmail.com"},
   {"username": "jen", 
  "email":"jenfer@gmail.com"},
   {"username": "anda", 
  "email":"anda@gmail.com"},
   {"username": "kent", 
  "email":"kent@gmail.com"}

]