#%RAML 1.0 NamedExample
  {
    "userid": 900,
    "email": "faye@hotmail.com",
    "date_joined": 1582747200000,
    "modified": 1582747201000,
    "type": 1,
    "deleted": false,
    "username": "fayz"
  }
  