#%RAML 1.0 NamedExample
      {
    "orderid": 105,
    "userid": 1010,
    "addressid": 210,
    "discounted": 5,
    "created": "2019-12-10T12:10:37.000+00:00",
    "modified": "null",
    "status": "Partially Shipped.",
    "amount": 9898
  }
