#%RAML 1.0 NamedExample
             
 
  {
    "productid": 100,
    "categoryid": 10,
    "name": "Amazon laptop",
    "description": "best batter life, 15' laptop, with a 1-year warranty",
    "video_url": "https://www.youtube.com/watch?v=3AtDnEC6zak",
    "price": 10000
  }
  