#%RAML 1.0 NamedExample
 {
    "productid": 111,
    "categoryid": 21,
    "name": "Nike",
    "description": "its the best shoes you will find in the world",
    "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
    "price": 1500
  }