#%RAML 1.0 DocumentationItem
title: rest user API Docomentation
content: This is user api doc. this raml doc provides all list of http methods and status code which are used during request and responce