#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: this api support basic authentication
describedBy:
  
  queryParameters:
   username:
     displayName: username
     type: string
     required: false
     description: api key to give authorization
   password:
     displayName: password
     type: string
     required: false
     description: api key to give authorization
     


    
    

