#%RAML 1.0 DataType
type: object
properties:
  addressid: string
  amount: integer
  date: integer
  day: string
  hours: integer
  minutes: integer
  month: integer
  nanos: integer
  seconds: integer
  time: integer
  timezoneOffset: string
  year: integer