#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/2ebf1790-78c3-478b-b66b-fec4702bfc67/ # 
title: ONLINE-SHOPPING-API
securitySchemes:
  basicAuth :
    type : Basic Authentication
types:
  customer : !include /userdatatype.raml 
  items : !include /productsdataType.raml
  order : !include /orderdataType.raml
  catagory : !include /catagorydataType.raml 
     
 

/users : 
 
 get:
   securedBy:
     - basicAuth
   responses:
    200:
        body:
          application/json:
            type: customer[]
            examples: !include example.raml
 post:
   body:
      application/json:
        examples: !include  example.raml
   responses:
      200:
        body:
          application/json:
            example:
              {
                "uid": 10
              }          

/users/{id} : 
   uriParameters:
    id:
      type: integer
   get:
     responses:
        200:
          body:
            application/json:
              examples: !include example.raml
              
   post:
      body:
        application/json:
          examples: !include example.raml

/products:
  get:
    responses:
      200:
        description: ok
        body:
          application/json:
            type: items[]
            examples: !include /products.raml
              
/products/{id} :
  uriParameters:
    id:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            examples: !include products.raml                  
/orders:
  get:
    responses:
      200:
        description: Ok
        body:
          application/json:
            examples: !include order.raml
   
  post:
    body:
      application/json:
        example:
          {
  "products": [
    {
      "productId": 2,
      "quantity": 5
    }
  ],
  "uid": 123
}
    responses:
      200:
        description: Ok
        body:
          application/json:
            example :
              "CREATED"
             
/orders/{uid}:
     get:
       responses:
        200:
          description: Ok
          body:
            application/json:
              examples: !include order.raml 
/orders/{id}:
    get:
     responses:
        200:
          description: Ok
          body:
            application/json:
              examples: !include order.raml 
/categories:
  get:
    responses:
      200:
        description: Ok
        body:
          application/json:
            examples: !include catagory.raml 
  /categories/{id} :
    get:
     responses:
        200:
          description: Ok
          body:
            application/json:
              examples: !include catagory.raml
                
              
 
       
         