#%RAML 1.0 Extension
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/e7e4fa74-638b-44ad-843a-2ca2abd2c6cc/ # 
usage: admin access only
extends: onlineApiDevelopment.raml
/users: 
  delete:
    description: this use admni only
      