#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/bf2cb2f6-dbe1-4f46-8f87-a107d7813589/ # 
title: usersapi
/users:
  get:
    responses:
      200:
        body:
          application/json:
            examples:
              {
                name:"bekalu",
                email:"bekalutilahun847@gamil.com"

    
              }
  post:
    responses:
      201:
        body:
          application/json:
            example:
             {name:"bekalu","mulugeta"

            }

  put:
    responses:
      200:
        body:
          application/json:
            examples:
              { name:"eyosias"}
  delete:
    responses:
      401:
        description: an authorized user
        

           


            
            
          
                        


        
      

                      
          
          

            

                      
              
            
    

      
  
      
        


 
   
