#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/7dd9a7f6-2da9-4bea-8d6e-73fe40becc58/ # 
title: onlineshopping
version: 1.o
mediaType: [Application/json]
annotationTypes:
  annotation: !include annotation/annotation.raml
types:
  users: !include types/users.raml
  user: !include types/user.raml
  products: !include types/products.raml
  product: !include types/product.raml
  orders: !include types/orders.raml
  order: !include types/order.raml
  categories: !include types/categories.raml
  category: !include types/category.raml
traits:
  responsemessage: !include traits/201.raml
  responsemessage1: !include traits/200.raml
  responsemessage2: !include traits//401.raml
  responsemessage3: !include traits/403.raml
  responsemessage4: !include traits/404.raml
securitySchemes:
  Oath: !include security/Oath.raml
documentation:
  - !include documentation/documentation.raml
/users:
  get:
    responses:
      200:
        body:
          application/json:
            type: users[]
            example: !include examples/users.raml
  post:
    body:
      application/json:
        example:
          {
                "email":"bella@gmail.com",
                "username":"bella"

          }
    responses:
        200:
          body:
            application/json:
              example:
                {"uid": 1089
                }
      #201:
        #body:
         # example:
         #     {"message":"created"}
  is:
    responsemessage:     
      404:
          body:
            application/json:
              example:
                {"message":"not found"}
      403:
          body:
            application/json:
              example:
                {"message":"forbidden"}
      401:
          body:
            application/json:
              example:
                {"message":"unauthorized"}
                   
/users/{id}:
  get:
    responses:
  is:
    responsemessage1:
        
/products:
  get:
    responses:
      200:
        body:
          application/json:
            type: products
            example: !include examples/products.raml
 
  
/products/{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: product
              example: !include examples/product.raml
        404:
          body:
            application/json:
              example:
                {"message":"not found"}
        403:
          body:
            application/json:
              example:
                {"message":"forbidden"}
        401:
          body:
            application/json:
              example:
                {"message":"unauthorized"}
     
/orders:
  get:
    responses:
      200:
        body:
          application/json:
            type: orders
            example: !include examples/orders.raml

  post:
    body:
      application/json:
        example:
          {
  "products": [
    {
      "productId": 103,
      "quantity": 20
    }
  ],
  "uid": 1089
}
    responses:
      200:
        body:
          application/json:
            example:
              {"uid": 1089
              }
      #201:
      # body:
      #   example:
      #       {"message":"created"}
  is:
    responsemessage:     
      404:
          body:
            application/json:
              example:
                {"message":"not found"}
      403:
          body:
            application/json:
              example:
                {"message":"forbidden"}
      401:
          body:
            application/json:
              example:
                {"message":"unauthorized"}
/orders/{id}:
  get:
    body:
      application/json:
        type: order
        example: !include examples/order.raml
 
/categories:
  get:
    responses:
      200:
        body:
          application/json:
            type: categories[]
            example: !include examples/categories.raml

/category/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: category
            example: !include examples/category.raml
  

