#%RAML 1.0 NamedExample
value:
- categoryid: 100
  description: Lenovo
  name: Laptop
  price: 1800
  productid: 101
  video_url: https://www.google.com/search?q=lenovo+laptop&oq=lenovo&aqs=chrome.1.69i57j0l7.6730j0j7&sourceid=chrome&ie=UTF-8
- categoryid: 300
  description: Lenovo
  name: Laptop
  price: 879
  productid: 150385
  video_url: https://www.google.com/search?q=lenovo+laptop&oq=lenovo&aqs=chrome.1.69i57j0l7.6730j0j7&sourceid=chrome&ie=UTF-8