#%RAML 1.0 NamedExample

     {        
      "productid": 103,
      "categoryid": 16,
      "name": "amazon essentials 15' laptop cover",
      "description": "The best you can get around in a handy design and funky look.",
      "video_url": "https://www.youtube.com/watch?v=3AtDnEC4zak",
      "price": 200
   }