#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f3661354-866d-4756-927a-52e7763dc8f6/ # 
title: Onlineshoping
/User:
  post:
    body:
      application/json:
        example:
          {"username":"test","email":"test@gmail.com"}
          
    responses:
      201:
        body:
          application/json:
            example:
              {"uid":"101"}
              
/Products:
  /{user}:
    get:
      responses:
        200:
          body:
            application/json:
              example:
                {
    "categoryid": 12,
    "description": "face mask",
    "name": "mask",
    "price": 15,
    "productid": 12,
    "video_url": "string"
  }

