#%RAML 1.0 NamedExample
[
  {
    "addressid": "23",
    "orderid": 15,
    "userid": 47,
    "discounted": 25,
    "created": 2018-11-26T16:17:18Z,
    "modified": "active",
    "status": "accepted",
    "amount": 300

    },
{
  
        "orderid": 15,
        "userid": 47,
        "addressid": "c25",
        "discounted": 25,
        "created": 2018-11-26T16:17:18Z,
        "modified": "active",
        "status": "accepted",
        "amount": 300

    
  }
]


