#%RAML 1.0 Trait
responses:
 401 :
   body:
     application/json:
       example:
         Unauthorized 
 403 :
   body:
     application/json:
       example: 	
         Forbidden
 404 : 
  body:
    application/json:
      example:
        resource not found

 