#%RAML 1.0 NamedExample
[{
  "orderid": 10,
  "userid": 26,
  "addressid": "Addis Ababa",
  "discounted": 1,
  "created": "2020-06-03T04:10:26.000+00:00",
  "modified": "null",
  "status": "Accepted",
  "amount": 6
} ,
{
"orderid": 13,
"userid": 15,
"addressid": "bil",
"discounted": 51,
"created": "2020-05-27T23:18:46.000+00:00",
"modified": "null",
"status": "accepted",
"amount": 1000

}]
