#%RAML 1.0 NamedExample

  valid: true
  number: "251912234406"
  local_format: "0912234406"
  international_format: "+251912234406"
  country_prefix: "+251"
  country_code: "ET"
  country_name: "Ethiopia (Federal Democratic Republic of)"
  location: "Addis"
  carrier: "Ethio Telecom"
  line_type: "mobile"

  # valid: true
  # number: "15713761371"
  # local_format: "5713761371"
  # international_format: "+15713761371"
  # country_prefix: "+1"
  # country_code: "US"
  # country_name: "United States of America"
  # location: "Herndon"
  # carrier: "T-Mobile USA Inc."
  # line_type: "mobile"



  

  

 
