#%RAML 1.0 ResourceType
get:
  description: this api can't return list of <<resourcePathName>>
  responses:
    404:
      body:
        application/json:
          example:
            {
              "message": " <<resourcePathNam>> not found"
            }
            

