#%RAML 1.0 NamedExample

values:
  -         
     categoryid": 10,
     name": "labtop"
  -
     categoryid": 11,
     name": "mouse"
  -
     categoryid": 12,
     name": "home electronics"
  -
     categoryid": 13,
     name": "mouse"
  -
     categoryid": 14,
     name": "labtop"