#%RAML 1.0 NamedExample

values:
  -    
     email: "tedy@gmail.com"     
     username: "Tedy"
  -
     email: "bear@gmail.com"     
     username: "bear"
  - 
     email: "david@gmail.com"     
     username: "David"
    
