#%RAML 1.0 NamedExample

{"productid":100,"categoryid":10,"name":"Amazon labtop","discription":"best batter life The mouse comes with a 1-year warranty","video_url":"https://www.youtube.com/embed/Ic-Y3osvnFk","price":1000}
